version: "3"

services:
  febtest-web-nginx:
    build: ./nginx
    container_name: febtest-web-nginx
    restart: always
    volumes: &febtest-web-volumes
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
     - febtest-web-php
     - febtest-mysql
    labels:
     - traefik.frontend.rule=Host:febtest.local
     - traefik.docker.network=traefik_default
    networks:
      - traefik_default
    expose:
      - "80"

  febtest-web-php:
    build: ./php
    container_name: febtest-web-php
    restart: always
    volumes: *febtest-web-volumes
    links:
      - febtest-mysql
    networks:
      - traefik_default

  febtest-mysql:
    build: ./mysql
    container_name: febtest-mysql
    restart: always
    env_file:
      - env/mysql.env
    volumes:
      - om-dbdata:/var/lib/mysql/
    networks:
      - traefik_default
    ports:
      - 3306:3306

volumes:
    om-dbdata:

networks:
    traefik_default:
      external: true